INSERT INTO car (brand, model, price, description) VALUES ('Acura', 'ILX', 75000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Acura', 'Integra', 100000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Acura', 'MDX', 60000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Acura', 'NSX', 10000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Acura', 'RDX', 132000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Acura', 'RL', 100000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Acura', 'RLX', 80000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Acura', 'TSX', 100000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Acura', 'M5', 130000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Audi', 'RS5', 100000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Audi', 'Q3', 100000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Audi', 'RS7', 100000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Audi', 'Q6', 240000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Audi', 'A3', 10000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Audi', 'S5', 40000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Audi', 'S7', 8000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Aston Martin', 'Cygnet', 100000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Aston Martin', 'DB11', 100000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Aston Martin', 'DB12', 100000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Aston Martin', 'DB9', 240000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Aston Martin', 'DBS', 10000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Aston Martin', 'Valkyrie', 40000.0);
INSERT INTO car (brand, model, price, description) VALUES ('Aston Martin', 'Valour', 8000.0);