create table car (
    id bigint generated by default as identity,
    body_type varchar(255) not null,
    brand varchar(255) not null,
    description clob not null,
    engine_capacity varchar(255) not null,
    engine_type varchar(255) not null,
    gearbox_type varchar(255) not null,
    mileage int not null,
    model varchar(255) not null,
    price decimal(19,2) not null,
    production_year int not null,
    primary key (id)
);

create table stock (
    product_id bigint not null,
    reserved int not null,
    stock int not null,
    primary key (product_id)
);

create table color (
    id bigint not null,
    name varchar(255) not null,
    primary key (id)
);

create table car_colors (
    car_id bigint not null,
    color_id bigint not null,
    primary key (car_id, color_id)
);

create table cart (
    id bigint not null,
    product long not null,
    quantity int not null,
    date date not null,
    description clob,
    primary key (id, product)
);

create table order_item (
   id bigint not null,
   order_id bigint not null,
   product_id long not null,
   quantity int not null,
   primary key (order_id, product_id)
);

create table order_header (
  order_id bigint not null AUTO_INCREMENT,
  sub_total decimal(19,2),
  delivery decimal(19,2),
  total decimal(19,2),
  first_name varchar(255),
  last_name varchar(255),
  adress varchar(255),
  phone varchar(255),
  description clob,
  primary key (order_id)
);